image: docker

services:
  - docker:dind

before_script:
  - docker version
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build
