image: tiangolo/docker-with-compose

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker version
  - docker-compose version  
  
build:
  stage: build
  script:
    - cd compose
    - docker-compose build
