image: docker:latest

services:
  - docker:dind

before_script:
  - apt-get install -y python-pip
  - pip install docker-compose
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build
