version: '3.5'
services:
  ordering:
    image: 'ordering:latest'
    build:
      context: ..
      dockerfile: src/services/ordering/Dockerfile
    container_name: ordering
    depends_on:
      - consul
    networks:
      microservices: null
  deliveries:
    image: 'deliveries:latest'
    build:
      context: ..
      dockerfile: src/services/deliveries/Dockerfile
    container_name: deliveries
    depends_on:
      - consul
    networks:
      microservices: null
  api.gateway:
    image: 'apigateway:latest'
    build:
      context: ..
      dockerfile: src/services/apigateway/Dockerfile
    container_name: apigateway
    depends_on:
      - consul
      - ordering
      - deliveries
    networks:
      microservices: null
  consul:
    image: 'consul:latest'
    hostname: consul
    container_name: consul
    networks:
      microservices: null
    volumes:
      - ./_data/consul/data/:/consul/data/
      - ./consul/config/:/consul/config/
  vault:
    container_name: vault
    hostname: vault
    image: vault:latest
    networks:
      microservices: null
    links:
      - 'consul:consul'
    depends_on:
      - consul
    ports:
      - '8200:8200'
    volumes:
      - ./_data/consul/data/:/consul/data/
      - ./consul/config/:/consul/config/
      - ./vault/config/:/config
    cap_add:
      - IPC_LOCK
    command: server -config=/config/vault.hcl
  vault-webui:
    container_name: vault-webui
    image: djenriquez/vault-ui
    hostname: vault-webui
    ports:
      - "8000:8000"
    links:
      - vault:vault
    networks:
      microservices: null
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      VAULT_URL_DEFAULT: http://vault:8200
  consul-backup:
    container_name: consul-backup
    build: backup/
    networks:
      microservices: null
    links:
      - consul:consul
    volumes:
      - ./_data/consul/backup:/backup/
    command: consul-backup
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - consul
    networks:
      microservices: null
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      microservices: null
networks:
  microservices:
    driver: bridge
volumes:
  prometheus:
    driver: local
  grafana:
    driver: local
  consul:
    driver: local
