version: '3.5'
services:

  ordering:
    image: 'ordering:latest'
    build:
      context: ..
      dockerfile: src/services/ordering/Dockerfile
    container_name: ordering
    depends_on:
      - consul
    networks:
      microservices: null

  deliveries:
    image: 'deliveries:latest'
    build:
      context: ..
      dockerfile: src/services/deliveries/Dockerfile
    container_name: deliveries
    depends_on:
      - consul
    networks:
      microservices: null

  api.gateway:
    image: 'apigateway:latest'
    build:
      context: ..
      dockerfile: src/services/apigateway/Dockerfile
    container_name: apigateway
    depends_on:
      - consul
      - ordering
      - deliveries
    networks:
      microservices: null

  consul:
    image: 'consul:latest'
    hostname: consul
    container_name: consul
    command: agent -config-dir=/consul/config -bind '{{ GetPrivateInterfaces | attr "address" }}' -client '{{ GetPrivateInterfaces | attr "address" }}' -bootstrap
    networks:
      microservices: null

  consul-agent:
    image: 'consul:latest'
    hostname: consul-agent
    container_name: consul-agent
    command: agent -join consul -config-dir=/consul/config -bind '{{ GetPrivateInterfaces | attr "address" }}' -client '{{ GetPrivateInterfaces | attr "address" }}'
    networks:
      microservices: null
    depends_on:
      - consul

  vault:
    container_name: vault
    hostname: vault
    image: vault:latest
    networks:
      microservices: null
    links:
      - 'consul:consul'
    depends_on:
      - consul

  consul-backup:
    container_name: consul-backup
    build:
      context: ..
      dockerfile: backup/Dockerfile
    networks:
      microservices: null
    links:
      - consul:consul
    volumes:
      - ./_data/consul/backup:/backup/
    command: consul-backup

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - consul
    networks:
      microservices: null

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      microservices: null

networks:
  microservices:
    driver: bridge

volumes:
  prometheus:
    driver: local
  grafana:
    driver: local
  consul:
    driver: local
