version: '3.5'

services:
  ordering:
    image: ordering:latest
    build:
      context: .
      dockerfile: services/ordering/Dockerfile
    container_name: ordering
    networks:
      microservices:

  deliveries:
    image: deliveries:latest
    build:
      context: .
      dockerfile: services/deliveries/Dockerfile
    container_name: deliveries
    networks:
      microservices:

  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: api.gateway/apigateway/Dockerfile
    container_name: apigateway
    networks:
      microservices:

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      microservices:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      microservices:

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      microservices:


networks:
  microservices:
    driver: 'bridge'