name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    name: Run Build on Ubuntu
    runs-on: ubuntu-latest
    uses: actions/checkout@v1
    steps:
    - name: Build the apigateway Docker image
      run: docker build . --file src/services/apigateway/Dockerfile --tag apigateway:$(date +%s)
    - name: Build the deliveries Docker image
      run: docker build . --file src/services/deliveries/Dockerfile --tag deliveries:$(date +%s)
    - name: Build the ordering Docker image
      run: docker build . --file src/services/ordering/Dockerfile --tag ordering:$(date +%s)      
